### ISSUE TITLE
use PointContatctDZ::Export2fieldgen() in example/pointContact/g2f.cc

### ISSUE THREAD

**Issue by jintonic** [jintonic/gefica#15]

**Comment by byljcron** [comment]
it still have some issue since the major data are still under protected flag, which means when we try to get value we do not know exact location and value of a grid point.

it is not a issue when we compare to MJD since MJD will provide grid set, but in the case when we are play with macro only, it can be a problem.

**Comment by jintonic** [comment]
I see. You are right. We need to setup a new grid in g2f.cc which is the same as a fieldgen setup that we want to compare to after g2f

**Comment by jintonic** [comment]
This is needed if somebody wants to use the fields calculated by GeFiCa as input for siggen.
